### ISSUE TITLE
[Bug] Read Questions

### ISSUE THREAD

**Issue by natec425** [destinymalone/reflection-api-starter#1]
https://github.com/destinymalone/reflection-api-starter/blob/63a110e4394dd129465d6b57db0da3859826ac9b/src/main/java/org/basecampcodingacademy/reflections/controllers/QuestionController.java#L17-L19

This code currently returns all Questions, but it should only return questions for the reflection identified by the id in the path.

**Comment by destinymalone** [comment]
@GetMapping
    public List<Question> index(Question question, @PathVariable Integer reflectionId) {
        question.reflectionId = reflectionId;
        return questions.reflectionQuestion(question);
    }
