### ISSUE TITLE
[Code Quality] Delete Commented Out Code

### ISSUE THREAD

**Issue by natec425** [destinymalone/reflection-api-starter#2]
https://github.com/destinymalone/reflection-api-starter/blob/63a110e4394dd129465d6b57db0da3859826ac9b/src/main/java/org/basecampcodingacademy/reflections/controllers/QuestionController.java#L28-L32

Commented out code should be generally be deleted. If code is commented out because we simply don't want it to run, it should be deleted for sure. If we are commenting it out because we want to leave some helpful note for maintainers in the future, we should say so with a helpful message beside the commented out code.

**Comment by destinymalone** [comment]
Deleted
