### ISSUE TITLE
[Code Quality] Unnecessary Type Cast

### ISSUE THREAD

**Issue by natec425** [destinymalone/reflection-api-starter#3]
https://github.com/destinymalone/reflection-api-starter/blob/63a110e4394dd129465d6b57db0da3859826ac9b/src/main/java/org/basecampcodingacademy/reflections/controllers/ResponseController.java#L30

This type cast is unnecessary. The ResponseRepository.getOne method already returns a List<Response>.

**Comment by destinymalone** [comment]
return responses.getOne(response);
