### ISSUE TITLE
[Code Quality] Misleading Method Name

### ISSUE THREAD

**Issue by natec425** [destinymalone/reflection-api-starter#4]
https://github.com/destinymalone/reflection-api-starter/blob/63a110e4394dd129465d6b57db0da3859826ac9b/src/main/java/org/basecampcodingacademy/reflections/db/ResponseRepository.java#L41-L43

This method returns a List<Response> but the name of the method is getOne. It should be renamed to appropriately inform the user about what it does.

**Comment by destinymalone** [comment]
What should I call it?

**Comment by destinymalone** [comment]
I changed the name.
